# Generated by Django 5.2.8 on 2025-11-25 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
        ('trees', '0003_treerecord_ai_analysis_treerecord_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0, help_text='Total points earned from verified tree records'),
        ),
        migrations.CreateModel(
            name='PointsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Points earned (can be negative for deductions)')),
                ('points_type', models.CharField(choices=[('tree_verified', 'Tree Record Verified'), ('bonus', 'Bonus Points'), ('achievement', 'Achievement Unlocked'), ('admin_adjustment', 'Admin Adjustment')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of why points were awarded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tree_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_logs', to='trees.treerecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
