# Generated by Django 5.2.8 on 2025-11-25 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('plant', 'Plant New Tree'), ('update', 'Update Tree Progress')], default='plant', max_length=10)),
                ('species', models.CharField(max_length=255)),
                ('tree_type', models.CharField(choices=[('fruit', 'Fruit Tree'), ('timber', 'Timber Tree'), ('medicinal', 'Medicinal Tree'), ('ornamental', 'Ornamental Tree'), ('windbreak', 'Windbreak'), ('shade', 'Shade Tree'), ('nitrogen_fixer', 'Nitrogen Fixer'), ('other', 'Other')], max_length=50)),
                ('location_description', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='trees/%Y/%m/%d/')),
                ('photo_datetime_original', models.DateTimeField(blank=True, help_text='DateTimeOriginal from EXIF', null=True)),
                ('photo_datetime_digitized', models.DateTimeField(blank=True, help_text='DateTimeDigitized from EXIF', null=True)),
                ('photo_datetime', models.DateTimeField(blank=True, help_text='DateTime from EXIF', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='trees_treer_created_b04356_idx'), models.Index(fields=['user', '-created_at'], name='trees_treer_user_id_4f2c66_idx')],
            },
        ),
    ]
