# Generated by Django 5.2.8 on 2025-11-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treerecord',
            name='gps_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treerecord',
            name='gps_img_direction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treerecord',
            name='gps_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
