# Generated by Django 5.2.8 on 2025-11-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_treerecord_gps_altitude_treerecord_gps_img_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treerecord',
            name='ai_analysis',
            field=models.TextField(blank=True, help_text='Detailed AI analysis from Groq'),
        ),
        migrations.AddField(
            model_name='treerecord',
            name='ai_confidence',
            field=models.CharField(blank=True, help_text='AI analysis confidence: high/medium/low', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treerecord',
            name='ai_tree_type',
            field=models.CharField(blank=True, help_text='Tree type identified by AI', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treerecord',
            name='authenticity_score',
            field=models.IntegerField(default=0, help_text='0-100: Authenticity score from AI analysis'),
        ),
        migrations.AddField(
            model_name='treerecord',
            name='gps_validation',
            field=models.BooleanField(default=True, help_text='GPS location matches tree type region'),
        ),
        migrations.AddField(
            model_name='treerecord',
            name='health_assessment',
            field=models.CharField(blank=True, help_text='Health assessment: Healthy/Good/Fair/Poor', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treerecord',
            name='image_quality',
            field=models.CharField(blank=True, help_text='Image quality: High/Medium/Low', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treerecord',
            name='is_authentic_image',
            field=models.BooleanField(default=True, help_text='Is the image authentic (not AI-generated/edited)?'),
        ),
        migrations.AddField(
            model_name='treerecord',
            name='verified',
            field=models.BooleanField(default=False, help_text='Record verified by admin'),
        ),
    ]
